import React from 'react';
import Head from 'next/head';
import { getSession } from 'next-auth/react';
import { NextPageContext } from 'next';
import Hero from '@/components/UI/Hero';
import Section1 from '@/components/UI/Section1';
import Section2 from '@/components/UI/Section2';
import Section3 from '@/components/UI/Section3';
import Section4 from '@/components/UI/Section4';
import Section5 from '@/components/UI/Section5';
import Footer from '@/components/UI/Footer';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='px-5 lg:px-14 bg_colorr'>
        <nav className='flex justify-between  py-5'>
          <img
            src='/images/logo.png'
            alt='Netflix Logo'
            className='h-5 md:h-10'
          />
          <div>
            <Link
              href='/auth'
              className='px-4 py-2 flex items-center rounded-md font-semibold text-sm bg-red-500 text-white hover:bg-red-700 transition duration-300'
            >
              Sign In
            </Link>
          </div>
        </nav>
        <Hero />
        <div className='bg_color rounded-3xl'>
          <Section1 />
          <Section2 />
          <Section3 />
          <Section4 />
        </div>
        <Section5 />
        <Footer />
      </div>
    </>
  );
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: '/home',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
